In [3]:
d = (3,'three',5,'five')
type(d)

tuple

In [4]:
d = {}
type(d)

dict

In [5]:
d = {3:'three',5:'five'}
type(d)

dict

In [7]:
d = {'3':'three','5':'five'}
type(d)

dict

In [17]:
people = {'hugh':49,'kate':35,'lucy':24,'bob':36, 'dan': 50} #144

total = 0
for x in people.values():
     total += x
        
total = sum(people.values())
total

194

In [15]:
total = sum(people.values())
total

144

In [20]:
people.keys()

dict_keys(['hugh', 'kate', 'lucy', 'bob', 'dan'])

In [22]:
peoplelist = [{'name':'bob','age':28},{'name':'dylan','age':43},{'name':'cat','age':17}]
for item in peoplelist:
    if item['age']>30:                
        print(item['name'])

dylan


In [28]:
def mystery(x):
    if x > 0:
        return -x
    else:
        return x
    
mystery(0)

0

In [32]:
import numpy as np
import numpy as np
c = np.array([[2,4,6,8],[12,14,16,18],[22,24,26,28]])
print(c)
np.shape(c)


[[ 2  4  6  8]
 [12 14 16 18]
 [22 24 26 28]]


(3, 4)

In [39]:
d = np.array([6,16,26])
d[d>10]=d

ValueError: NumPy boolean array indexing assignment cannot assign 3 input values to the 2 output values where the mask is true

In [48]:
from datetime import datetime
import datetime
D1 = datetime(2017,2,22,9,30)
D2 = datetime(2017,2,23,10,45)
D2 - D1
D1.strftime()

TypeError: 'module' object is not callable

In [66]:
word_freq = {'the':58, 'people':6, 'beautiful':8, 
             'cats':13, 'finally':9, 'this': 19, 'class': 21, 
             'is': 101, 'almost': 1, 'over':4} #Store dict

def top_words(word_freq, threshold = 10):
    print('-------------------------------------------')
    print('Display words greater than threshold = {}'.format(threshold)) #basic logs
    print('-------------------------------------------') 
    counter = 1
    for key,value in word_freq.items():
        if value > threshold: #conditional logic
            print('{} Word: {}        Count {}'.format(counter, key, value))
            counter +=1
    print('-------------------------------------------')
            
thresh = [10,50,100]           
            
for i in thresh: #Lopp through thresh list to run function multiple times
    top_words(word_freq = word_freq, threshold= i)

-------------------------------------------
Display words greater than threshold = 10
-------------------------------------------
1 Word: the        Count 58
2 Word: cats        Count 13
3 Word: this        Count 19
4 Word: class        Count 21
5 Word: is        Count 101
-------------------------------------------
-------------------------------------------
Display words greater than threshold = 50
-------------------------------------------
1 Word: the        Count 58
2 Word: is        Count 101
-------------------------------------------
-------------------------------------------
Display words greater than threshold = 100
-------------------------------------------
1 Word: is        Count 101
-------------------------------------------


In [210]:
import os
import pandas as pd
cwd = os.getcwd() #get cwd
path = os.listdir(cwd)[1] #index on .csv needed
#Rename columns on load. Slice on index. Remove junk at the beginning and end
#Also note keep default na parm. This defaults so that all blanks are set to NaNs. This breaks the next step
data = pd.read_csv(path, names = ['Jan89', 'Jan90', 'Jan91', 'Jan92', 'Jan93', 'Jan94', 'Jan95'], keep_default_na=False)[3:-4]
#Replace blank values with 0
data.replace('', 0, inplace= True)

#Note that Country is the index here
data.reset_index(inplace = True)

#Iterrows lets you iterate through a dataframe 
print('------------------------------------------------------------')
print('Printing all countries with a population above 1mm in Jan1995')
print('------------------------------------------------------------')
for (idx, row) in data.iterrows():
    if int(row['Jan95']) > 1000000: #conditional logic
        print('Country: {}        Population: {}'.format(row['index'], row['Jan95'])) #str formatting
        


sliced= data[data['index'] == 'United Kingdom'] #Extract row for index == UK
sliced = pd.DataFrame(sliced.iloc[:, [1,2,3,4,5,6,7]], dtype = int) #Drop 1st col. Transform to all int dtypes
avg = int(sliced.mean(axis = 1)) #find mean using pandas

print('------------------------------------------------------------')
print('Average population of United Kingdom from Jan89-Jan95:', avg)






------------------------------------------------------------
Printing all countries with a population above 1mm in Jan1995
------------------------------------------------------------
Country: Austria        Population: 8054800
Country: Belgium        Population: 10143047
Country: Denmark        Population: 5251027
Country: Finland        Population: 5116800
Country: France        Population: 58265400
Country: Germany        Population: 81845000
Country: Ireland        Population: 3591200
Country: Italy        Population: 57268578
Country: Netherland        Population: 15492800
Country: Norway        Population: 4370000
Country: Portugal        Population: 9920800
Country: Spain        Population: 39241900
Country: Sweden        Population: 8837000
Country: Switzerland        Population: 7060400
Country: United Kingdom        Population: 58684000
------------------------------------------------------------
Average population of United Kingdom from Jan89-Jan95: 58062861
